"""Run the shared conformance suite (spec/conformance) through the Python API.

The same files are run by the Rust and JS test suites. The random cases were
generated by this implementation, but the hand-written error cases were not. So
this harness checks that the Python API and the JSON plumbing agree with the
spec, and not only with themselves.
"""

from __future__ import annotations

import json
import subprocess
import sys
from collections.abc import Callable
from pathlib import Path
from typing import Any

import pytest

from wiring_diagrams import (
    Star,
    WiringDiagram,
    WiringError,
    eq,
    evaluation,
    externalize,
    internal_hom,
    internalize,
    rel,
)

ROOT = Path(__file__).resolve().parents[2]
CONFORMANCE = ROOT / "spec" / "conformance"

D = WiringDiagram.from_json


def run_stars(c: dict[str, Any]) -> Any:
    return list(Star.from_json(c["wires"]).names)


def run_canonical(c: dict[str, Any]) -> Any:
    return D(c["input"]).to_json()


def run_identity(c: dict[str, Any]) -> Any:
    return WiringDiagram.identity(Star.from_json(c["star"])).to_json()


def run_compose(c: dict[str, Any]) -> Any:
    return D(c["diagram"]).compose([D(k) for k in c["children"]]).to_json()


def run_permute(c: dict[str, Any]) -> Any:
    return D(c["diagram"]).permute(c["sigma"]).to_json()


def run_map_types(c: dict[str, Any]) -> Any:
    return D(c["diagram"]).map_types(c["mapping"].__getitem__).to_json()


def run_closed(c: dict[str, Any]) -> Any:
    op = c["op"]
    if op == "internal_hom":
        return internal_hom([Star.from_json(y) for y in c["ys"]], Star.from_json(c["z"])).to_json()
    if op == "evaluation":
        return evaluation([Star.from_json(y) for y in c["ys"]], Star.from_json(c["z"])).to_json()
    if op == "internalize":
        return internalize(D(c["diagram"]), c["m"]).to_json()
    if op == "externalize":
        ys = [Star.from_json(y) for y in c["ys"]]
        return externalize(D(c["diagram"]), ys, Star.from_json(c["z"])).to_json()
    raise AssertionError(op)


def run_rel(c: dict[str, Any]) -> Any:
    phi = D(c["diagram"])
    if len(c["relations"]) != phi.arity:
        return rel.apply(phi, [], c["domains"]).to_json()  # raises arity_mismatch
    rs = [rel.Relation.from_json(x, r) for x, r in zip(phi.inner, c["relations"], strict=True)]
    return rel.apply(phi, rs, c["domains"]).to_json()


def run_eq(c: dict[str, Any]) -> Any:
    phi = D(c["diagram"])
    ps = [eq.Partition(x, p) for x, p in zip(phi.inner, c["partitions"], strict=True)]
    return list(eq.apply(phi, ps).blocks)


RUNNERS: dict[str, Callable[[dict[str, Any]], Any]] = {
    "stars": run_stars,
    "canonical": run_canonical,
    "identity": run_identity,
    "compose": run_compose,
    "permute": run_permute,
    "map_types": run_map_types,
    "closed": run_closed,
    "rel": run_rel,
    "eq": run_eq,
}


def normalise(family: str, value: Any) -> Any:
    """Relations are sets: compare their rows order-insensitively."""
    if family == "rel":
        return {"wires": value["wires"], "rows": sorted(map(json.dumps, value["rows"]))}
    return value


def cases() -> list[Any]:
    out = []
    for family in RUNNERS:
        data = json.loads((CONFORMANCE / f"{family}.json").read_text(encoding="utf-8"))
        out += [pytest.param(family, c, id=f"{family}-{i}") for i, c in enumerate(data["cases"])]
    return out


@pytest.mark.parametrize(("family", "case"), cases())
def test_case(family: str, case: dict[str, Any]) -> None:
    run = RUNNERS[family]
    if "error" in case:
        with pytest.raises(WiringError) as e:
            run(case)
        assert e.value.kind == case["error"]
    else:
        assert normalise(family, run(case)) == normalise(family, case["expected"])


def test_generated_files_are_current() -> None:
    result = subprocess.run(
        [sys.executable, str(ROOT / "scripts" / "generate.py"), "--check"],
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stdout + result.stderr
